import yfinance as yf
import numpy as np
from datetime import datetime
from dateutil.relativedelta import relativedelta

# Get today's date
today = datetime.now().date()


def n_consecutive_green_history(
    n: int,
    ticker: str,
    lookback_months: int,
):

    lookback_months = today - relativedelta(months=lookback_months)

    df = yf.download(f"{ticker}.NS", start=str(lookback_months), progress=False)
    df["Color"] = np.where(df["Close"] > df["Open"], "G", "R")

    data = []
    count = 0

    for i in range(len(df)):
        if df["Color"].iloc[i] == "G":
            count += 1
            if count == 1:
                first_date = df.index[i]
                open_price = df["Open"].iloc[i]
            if count >= n:
                if (str(first_date.date()),float(open_price)) not in data:
                    data.append((str(first_date.date()),float(open_price)))
        else:
            count = 0

    print(f"Stock : {ticker}")
    for i in data:
        print(f"     {n} consecutive green candles start date {i[0]} and open price {i[1]}")
        

tickers = ['ABFRL', 'AFFLE', 'ACE', 'AARTIIND', 'ACC', 'ADANIGREEN', 'ADANIENSOL', 'ABCAPITAL', 'ADANIPORTS', 'ABB', 'AEGISLOG', 'ADANIPOWER', 'ADANIENT', '3MINDIA', 'ABBOTINDIA', 'AIAENG', 'ATGL', 'AAVAS', 'ARE&M', 'AJANTPHARM', 'ALKYLAMINE', 'APOLLOTYRE', 'AMBER', 'AMBUJACEM', 'ALKEM', 'ALLCARGO', 'APLLTD', 'APOLLOHOSP', 'APARINDS', 'ALOKINDS', 'APLAPOLLO', 'ASTRAZEN', 'ASTRAL', 'ASTERDM', 'ATUL', 'AXISBANK', 'AUROPHARMA', 'ASAHIINDIA', 'ASIANPAINT', 'AUBANK', 'AVANTIFEED', 'ASHOKLEY', 'BDL', 'BHARATFORG', 'BAJAJFINSV', 'BERGEPAINT', 'BATAINDIA', 'BAJAJ-AUTO', 'BALKRISIND', 'BALRAMCHIN', 'BANDHANBNK', 'BEML', 'BANKINDIA', 'BANKBARODA', 'BBTC', 'BAJFINANCE', 'BAYERCROP', 'BAJAJHLDNG', 'BEL', 'BALAMINES', 'BRIGADE', 'BSOFT', 'BLUEDART', 'BRITANNIA', 'BIOCON', 'BIRLACORPN', 'BORORENEW', 'BLS', 'CANFINHOME', 'BHEL', 'BOSCHLTD', 'BHARTIARTL', 'BLUESTARCO', 'BSE', 'CANBK', 'BPCL', 'ZYDUSLIFE', 'CENTURYPLY', 'CDSL', 'CGCL', 'CGPOWER', 'CHALET', 'CARBORUNIV', 'CEATLTD', 'CESC', 'CIPLA', 'CAPLIPOINT', 'CCL', 'COALINDIA', 'CENTURYTEX', 'COROMANDEL', 'CASTROLIND', 'CHENNPETRO', 'COFORGE', 'COLPAL', 'CONCOR', 'CHOLAHLDNG', 'COCHINSHIP', 'CENTRALBK', 'CHAMBLFERT', 'JWL', 'CHOLAFIN', 'CERA', 'DABUR', 'CYIENT', 'DALBHARAT', 'DEEPAKNTR', 'CUMMINSIND', 'DEEPAKFERT', 'CSBBANK', 'CRISIL', 'CROMPTON', 'DCMSHRIRAM', 'CREDITACC', 'CUB', 'DMART', 'DLF', 'ELECON', 'ELGIEQUIP', 'DIXON', 'ECLERX', 'EIHOTEL', 'EIDPARRY', 'DRREDDY', 'EMAMILTD', 'DIVISLAB', 'EICHERMOT', 'FLUOROCHEM', 'ENGINERSIN', 'FINCABLES', 'FACT', 'FINPIPE', 'ESCORTS', 'GAEL', 'GAIL', 'ERIS', 'FORTIS', 'FSL', 'FEDERALBNK', 'FINEORG', 'ENDURANCE', 'FDC', 'EPL', 'EXIDEIND', 'GMMPFAUDLR', 'GODFRYPHLP', 'GILLETTE', 'GLENMARK', 'GNFC', 'GICRE', 'GESHIP', 'GMDCLTD', 'GODREJCP', 'GMRINFRA', 'GLAXO', 'GODREJIND', 'GODREJPROP', 'HAL', 'GRANULES', 'HAPPSTMNDS', 'GRINDWELL', 'GRSE', 'GSPL', 'GUJGASLTD', 'HAVELLS', 'HBLPOWER', 'GPIL', 'GRASIM', 'GSFC', 'GPPL', 'GRAPHITE', 'HINDALCO', 'HUDCO', 'HINDPETRO', 'HINDZINC', 'HDFCBANK', 'HDFCLIFE', 'HINDCOPPER', 'HSCL', 'SAMMAANCAP', 'HCLTECH', 'HINDUNILVR', 'HEG', 'HFCL', 'HEROMOTOCO', 'HDFCAMC', 'HONAUT', 'ICICIBANK', 'IDEA', 'IDBI', 'IDFCFIRSTB', 'IGL', 'INDIACEM', 'INDIANB', 'ICICIGI', 'IDFC', 'INDIGO', 'ICICIPRULI', 'IIFL', 'INDHOTEL', '360ONE', 'IEX', 'INDIAMART', 'IRCON', 'ITI', 'J&KBANK', 'IRCTC', 'INTELLECT', 'ISEC', 'ITC', 'JAIBALAJI', 'INDUSTOWER', 'IOB', 'INOXWIND', 'INFY', 'INDUSINDBK', 'IRB', 'IOC', 'IPCALAB', 'JSL', 'JUBLFOOD', 'KANSAINER', 'JINDALSAW', 'JKCEMENT', 'JSWSTEEL', 'JUSTDIAL', 'JBMA', 'JSWENERGY', 'JUBLPHARMA', 'JYOTHYLAB', 'JBCHEPHARM', 'JKLAKSHMI', 'KPIL', 'JMFINANCIL', 'KAJARIACER', 'JINDALSTEL', 'JKPAPER', 'KEI', 'KOTAKBANK', 'KPRMILL', 'KARURVYSYA', 'KEC', 'KNRCON', 'KPITTECH', 'KRBL', 'LT', 'LALPATHLAB', 'M&MFIN', 'LTIM', 'LAURUSLABS', 'KSB', 'LINDEINDIA', 'LICHSGFIN', 'M&M', 'LEMONTREE', 'LTTS', 'LTF', 'LUPIN', 'MCX', 'POONAWALLA', 'CIEINDIA', 'MARICO', 'MAHLIFE', 'MAHSEAMLES', 'MAXHEALTH', 'MASTEK', 'MAHABANK', 'MANAPPURAM', 'UNITDSPR', 'MARUTI', 'METROPOLIS', 'MMTC', 'MOTHERSON', 'MRPL', 'MFSL', 'MHRIL', 'MINDACORP', 'MOTILALOFS', 'MPHASIS', 'MRF', 'UNOMINDA', 'MGL', 'NHPC', 'NBCC', 'NH', 'NAVINFLUOR', 'NATIONALUM', 'NATCOPHARM', 'MUTHOOTFIN', 'NAM-INDIA', 'NCC', 'NESTLEIND', 'NAUKRI', 'NETWORK18', 'NIACL', 'OIL', 'OFSS', 'NMDC', 'ONGC', 'NLCINDIA', 'OBEROIRLTY', 'RHIM', 'NTPC', 'OLECTRA', 'PAGEIND', 'PFC', 'PEL', 'PGHH', 'PHOENIXLTD', 'PIDILITIND', 'PETRONET', 'PERSISTENT', 'PNB', 'PCBL', 'PIIND', 'PNBHOUSING', 'PRESTIGE', 'PRINCEPIPE', 'POWERGRID', 'PNCINFRA', 'POWERINDIA', 'PRAJIND', 'POLYCAB', 'PVRINOX', 'QUESS', 'PRSMJOHNSN', 'POLYMED', 'RADICO', 'RBLBANK', 'RAYMOND', 'RELIANCE', 'RITES', 'RAJESHEXPO', 'RCF', 'RKFORGE', 'REDINGTON', 'RECLTD', 'RENUKA', 'RAMCOCEM', 'RATNAMANI', 'SAIL', 'SAREGAMA', 'PATANJALI', 'SBICARD', 'RTNINDIA', 'ROUTE', 'RVNL', 'SANOFI', 'SAFARI', 'SBIN', 'SCHAEFFLER', 'SCHNEIDER', 'SHREECEM', 'SBILIFE', 'SOLARINDS', 'SPARC', 'SIEMENS', 'SKFINDIA', 'SOBHA', 'SJVN', 'SONATSOFTW', 'SHRIRAMFIN', 'SUNDARMFIN', 'SUNTECK', 'SUNPHARMA', 'SUMICHEM', 'SUNTV', 'SRF', 'SUNDRMFAST', 'STLTECH', 'SUPREMEIND', 'TATAPOWER', 'TANLA', 'TATAELXSI', 'TATASTEEL', 'SUVENPHAR', 'TEJASNET', 'TATACHEM', 'SUZLON', 'TATACOMM', 'SWSOLAR', 'SYNGENE', 'TATACONSUM', 'TATAMOTORS', 'SWANENERGY', 'TCS', 'TATAINVEST', 'TECHM', 'TITAN', 'TRITURBINE', 'TTML', 'TORNTPOWER', 'TRIDENT', 'TV18BRDCST', 'THERMAX', 'TRIVENI', 'UCOBANK', 'TORNTPHARM', 'TVSMOTOR', 'UBL', 'TRENT', 'TIINDIA', 'TIMKEN', 'TITAGARH', 'UJJIVANSFB', 'UPL', 'VEDL', 'VBL', 'ULTRACEMCO', 'VGUARD', 'UNIONBANK', 'USHAMART', 'VAIBHAVGBL', 'VARROC', 'WHIRLPOOL', 'WELCORP', 'VIPIND', 'WESTLIFE', 'ZFCVINDIA', 'WIPRO', 'WELSPUNLIV', 'VTL', 'VOLTAS', 'ZEEL', 'ZENSARTECH', 'YESBANK', 'LLOYDSME', 'CAMS', 'ANGELONE', 'UTIAMC', 'MAZDOCK', 'EQUITASBNK', 'GLAND', 'RBA', 'IRFC', 'INDIGOPNTS', 'HOMEFIRST', 'RAILTEL', 'MTARTECH', 'EASEMYTRIP', 'JUBLINGREA', 'ANURAS', 'CRAFTSMAN', 'LXCHEM', 'KALYANKJIL', 'LODHA', 'SHYAMMETL', 'SONACOMS', 'KIMS', 'CLEAN', 'ZOMATO', 'GLS', 'DEVYANI', 'CHEMPLASTS', 'NUVOCO', 'APTUS', 'VIJAYA', 'NYKAA', 'POLICYBZR', 'SAPPHIRE', 'PAYTM', 'LATENTVIEW', 'STARHEALTH', 'ANANDRATHI', 'MAPMYINDIA', 'METROBRAND', 'MEDPLUS', 'DATAPATTNS', 'AWL', 'MANYAVAR', 'MSUMI', 'CAMPUS', 'RAINBOW', 'LICI', 'DELHIVERY', 'AETHER', 'SYRMA', 'TMB', 'PPLPHARMA', 'MEDANTA', 'BIKAJI', 'ACI', 'KAYNES', 'FIVESTAR', 'KFINTECH', 'NSLNISP', 'MANKIND', 'SBFC', 'CONCORDBIO', 'JIOFIN', 'TVSSCS', 'RRKABEL', 'NUVAMA', 'SIGNATURE', 'JSWINFRA', 'CELLO', 'HONASA', 'TATATECH', 'DOMS', 'HAPPYFORGE']

for _ in tickers:
    n_consecutive_green_history(4, _, 6)
